In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("housing.csv")

In [3]:
df.shape

(505, 1)

In [4]:
df.head(5)

  0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
0   0.02731   0.00   7.070  0  0.4690  6.4210  78...
1   0.02729   0.00   7.070  0  0.4690  7.1850  61...
2   0.03237   0.00   2.180  0  0.4580  6.9980  45...
3   0.06905   0.00   2.180  0  0.4580  7.1470  54...
4   0.02985   0.00   2.180  0  0.4580  6.4300  58...

In [5]:
df.tail(5)

    0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
500   0.06263   0.00  11.930  0  0.5730  6.5930  69...
501   0.04527   0.00  11.930  0  0.5730  6.1200  76...
502   0.06076   0.00  11.930  0  0.5730  6.9760  91...
503   0.10959   0.00  11.930  0  0.5730  6.7940  89...
504   0.04741   0.00  11.930  0  0.5730  6.0300  80...

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.shape

(505, 1)

In [8]:
df.isna().sum()

0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00    0
dtype: int64

In [9]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='mean')
imputer.fit(df[['']])

KeyError: "None of [Index([''], dtype='object')] are in the [columns]"

In [ ]:
imputer.statistics_

array([5403.45928339])

In [ ]:
df['Applicant_Income']=imputer.transform(df[['Applicant_Income']])